"""
Apache Thrift — Server Implementation
Topic 1: Apache Thrift Study

RPC Architecture mapping:
  Client Program → Client Stub (generated) → [TCP:9090] → Server Stub (generated) → MathServiceHandler

SETUP:
  pip install thrift
  thrift --gen py sum_service.thrift   # generates gen-py/sum_service/

RUN:
  python server.py
"""

import sys
import os

# Add generated stubs to path (generated by: thrift --gen py sum_service.thrift)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "gen-py"))

from thrift.transport import TSocket, TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

# Import generated stubs (Server Stub interface + data types)
from sum_service import MathService
from sum_service.ttypes import MathResult, DivisionByZeroException


# ─── Server Program ───────────────────────────────────────────────────────────
# This class is the "Server Program" in the RPC architecture.
# The Thrift-generated Server Stub calls these methods after unmarshalling.

class MathServiceHandler:
    """
    Implements the MathService interface defined in sum_service.thrift.
    This is pure business logic — no networking code needed here.
    """

    def remoteSum(self, request):
        """remote_sum(a, b) — the course example."""
        print(f"[Thrift] remoteSum({request.a}, {request.b})")
        result = request.a + request.b
        return MathResult(
            result=result,
            expression=f"{request.a} + {request.b}",
            operation="sum",
        )

    def remoteDivide(self, request):
        """remote_divide — typed exception propagated across the network."""
        print(f"[Thrift] remoteDivide({request.a}, {request.b})")
        if request.b == 0:
            # Thrift marshals this exception and sends it to the client,
            # where it is re-raised as a DivisionByZeroException.
            raise DivisionByZeroException(message="Division by zero is not allowed")
        return MathResult(
            result=request.a / request.b,
            expression=f"{request.a} / {request.b}",
            operation="divide",
        )

    def remoteMultiply(self, request):
        print(f"[Thrift] remoteMultiply({request.a}, {request.b})")
        return MathResult(
            result=request.a * request.b,
            expression=f"{request.a} * {request.b}",
            operation="multiply",
        )

    def remoteSubtract(self, request):
        print(f"[Thrift] remoteSubtract({request.a}, {request.b})")
        return MathResult(
            result=request.a - request.b,
            expression=f"{request.a} - {request.b}",
            operation="subtract",
        )

    def getServerInfo(self):
        return (
            '{"service": "Math Thrift Service", "version": "1.0.0", '
            '"protocol": "Thrift Binary over TCP", "port": 9090}'
        )


# ─── Server Setup ─────────────────────────────────────────────────────────────
def serve():
    handler = MathServiceHandler()

    # Server Stub (generated by Thrift compiler)
    processor = MathService.Processor(handler)

    # Transport layer — TCP socket
    transport = TSocket.TServerSocket(host="localhost", port=9090)
    t_factory = TTransport.TBufferedTransportFactory()

    # Protocol — Binary (compact binary serialization, not JSON/XML)
    p_factory = TBinaryProtocol.TBinaryProtocolFactory()

    server = TServer.TSimpleServer(processor, transport, t_factory, p_factory)

    print("Apache Thrift MathService running on localhost:9090")
    print("Protocol: Binary (compact, not human-readable — unlike JSON-RPC/XML-RPC)")
    print("Architecture: Client → ClientStub → [TCP] → ServerStub → MathServiceHandler")
    print("\nAvailable procedures: remoteSum, remoteDivide, remoteMultiply, remoteSubtract")
    print("Press Ctrl+C to stop.\n")
    server.serve()


if __name__ == "__main__":
    serve()
